PRODUCT_SMALL = 20
PRODUCT_MEDIUM = 30
PRODUCT_BIG = 40
PRODUCT_GIANT = 50
PRODUCT_SIZES = (
    (PRODUCT_SMALL, 'PRODUCT_SMALL'),
    (PRODUCT_MEDIUM, 'PRODUCT_MEDIUM'),
    (PRODUCT_BIG, 'PRODUCT_BIG'),
    (PRODUCT_GIANT, 'PRODUCT_GIANT'),
)

PRODUCT_TECH = 1
PRODUCT_CLOTHE = 2
PRODUCT_FOOD = 3
PRODUCT_TYPES = (
    (PRODUCT_TECH, 'PRODUCT_TECH'),
    (PRODUCT_CLOTHE, 'PRODUCT_CLOTHE'),
    (PRODUCT_FOOD, 'PRODUCT_FOOD'),
)

SERVICE_DELIVERY = 1
SERVICE_CAR = 2
SERVICE_HAIR = 3
SERVICE_TYPES = (
    (SERVICE_DELIVERY, 'SERVICE_DELIVERY'),
    (SERVICE_CAR, 'SERVICE_CAR'),
    (SERVICE_HAIR, 'SERVICE_HAIR'),
)