# Generated by Django 2.2.5 on 2019-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.PositiveSmallIntegerField(choices=[(20, 'PRODUCT_SMALL'), (30, 'PRODUCT_MEDIUM'), (40, 'PRODUCT_BIG'), (50, 'PRODUCT_GIANT')], default=30)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'PRODUCT_TECH'), (2, 'PRODUCT_CLOTHE'), (3, 'PRODUCT_FOOD')], default=3)),
                ('existence', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('-price',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'SERVICE_DELIVERY'), (2, 'SERVICE_CAR'), (3, 'SERVICE_HAIR')], default=1)),
                ('approximate_duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'ordering': ('-price',),
            },
        ),
    ]
